### ISSUE TITLE
[Feature] add support for multiple accounts at different servers

### ISSUE THREAD

**Issue by yahooooza** [astubenbord/paperless-mobile#13]
Paperless -ngx doesnt have a good way to seperate documents between users. In that case it can be usefull to set up multiple instances of paperless to do that. A way to quickly switch between accounts would be a nice to have. Thanks in advance :D.

**Comment by astubenbord** [comment]
Thanks for the idea, I was also thinking about something similar. Just to be clear, you simply want a mechanism so that a single user can switch between different accounts on different servers, right? So the app just has to store different login information (server address, username, password, and optionally client certs) which a single user can quickly switch between?

**Comment by yahooooza** [comment]
Yes exactly.

**Comment by astubenbord** [comment]
I think given the progress in https://github.com/paperless-ngx/paperless-ngx/discussions/295 I would prefer to wait before I implement sth. that is essentially just a workaround for an even more encompassing feature. Switching between servers would not really stand in the way of a multi user support feature, however, I just think that many users have it set up this way (multiple instances for multiple users) because it is currently not natively supported.
