### ISSUE TITLE
[BUG+Feature Request] Gray Screen instead of Settings

### ISSUE THREAD

**Issue by bertoo87** [astubenbord/paperless-mobile#161]
Settings screen stays gray and is non-responsive

**To Reproduce**
1. Go to the burger menu
2. Click on "Settings
3. Screen is completely gray, nothing visible except the back arrow and the word "Settings" at the top, but its completely unresponsive

**Expected behavior**
well - see a settings screen :)

**Device Information:**
 - Device: Google Pixel 7 Pro
 - OS: Android 13
 - Paperless Mobile version 2.1.0+27
 - Paperless Server version 1.14.2

**Feature Request**
Ability to add a 2nd. instance / server adress. i dont want to open it to the internet, but would still like to access it on the go with the help of Tailscale, which would require me to log out and connect with the tunnel IP at the moment. So a 2nd Server adress (connecting the one reachable) would be awesome. Or a 2nd instance.

**Comment by astubenbord** [comment]
Hi, the app version 2.1.0 does not yet support paperless 1.14. There is an open beta on google play you can join, which adds multi user/instance support (click on the avatar in the search bar and press "add account") and fixes the grey screen issue. 

The paperless 1.14 update broke some APIs, and I currently don't have enough time to fix this quickly. I'm working on full support for user permissions, but since it's quite a big update it will take some time, I'll keep the open beta updated until it's stable enough to release a new "official" version. But please keep in mind that some features (apparently upload and saving) currently don't work due to the paperless update, as the API expects the owner to be sent with each request.
