### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dannytsang** [astubenbord/paperless-mobile#163]
**Describe the bug**
Settings page shows a grey screen with nothing on it.

**To Reproduce**
1. Go to menu 
2. Click on Settings

**Expected behavior**
Something to be there.

**Screenshots**
![Screenshot_20230506-110816.png](https://user-images.githubusercontent.com/567982/236617872-433ad612-f18c-4349-aff6-c88c17e2bee9.png)

**Device Information:**
 - Device: Pixel 7 Pro
 - OS: Android 13
 - Paperless Mobile version 2.1.0+27
 - Paperless Server version 1.14.4
**Additional context**
I was looking for a date format setting because it's using USA rather my prefer locale (GB) or ISO 8601.

**Comment by astubenbord** [comment]
See #122.

Unfortuntately, the new update broke some endpoints and therefore some requests now throw errors or just don't return any values, which causes these screens to happen. This is fixed in 2.2.0+28, but there are still things that don't work due to the major update pushed in 1.14 (e.g. editing and saving documents, uploading documents etc.). I'm working on it though, but it might take a while because it requires a major redesign and I have to support older versions previous to 1.14 as well.

**Comment by dannytsang** [comment]
Just installed the beta and confirm it's fixed. Thanks @astubenbord
