### ISSUE TITLE
[BUG] "Labels" section does not work

### ISSUE THREAD

**Issue by n7298174289** [astubenbord/paperless-mobile#203]
**Describe the bug**
The "Labels" section does not work. No correspondents, document types and tags are shown to me, although I have some on my Paperless system. I don't know if storage paths are displayed because I don't have any.

**To Reproduce**
1. Go to 'Labels'
2. Click on 'Document Types'
3. No document types are displayed. 
"No document types have been created yet." / "Es wurden noch keine Dokumenttypen angelegt."

**Expected behavior**
My document types should be displayed here.

**Screenshots**
![Screenshot_20230612_210047](https://github.com/astubenbord/paperless-mobile/assets/93689511/6e78674c-5219-451e-bbe9-8e0fb092c934)

**Device Information:**
 - Device: [Samsung Galaxy S21 5G]
 - OS: [e.g. Android 13]
 - Paperless Mobile version [2.1.0]
 - Paperless Server version [1.15.1; paperless-ngx on UnRAID]

**Additional context**
When I create document types in the app, they are displayed and exist on the Paperless web interface as well. In the app, all other document types are still not displayed.
I have already tried reinstalling the app.

**Comment by astubenbord** [comment]
Hi, I see you are still on a rather old version of the app. We currently have newer versions in an open beta, but I'll make them the default now. The behavior you're reporting was reported before and fixed in 2.3.2 I think.

I just requested the beta to be promoted to production with 2.3.5, maybe keep an eye open for updates, should be up in a couple of hours. 


I'll close this as completed. If you have further questions, just reply in this thread.

Cheers
