### ISSUE TITLE
[BUG] Login Error

### ISSUE THREAD

**Issue by htpnikon** [astubenbord/paperless-mobile#215]
**Describe the bug**
Nach der Neuinstallation vom paperless-mobile muss die IP-Adresse vom Server eingegeben werden um zum nächsten Schritt "Eingabe der Login-Daten" zu kommen. Nach der eingabe der IP wird "Verbindung erfolgreich hergestellt" angezeigt. Soweit so gut. Nach der Eingabe der Login-Daten und bestätigen mit den Button Anmelden komm eine Fehlermeldung: type 'String' is not a subtype of 'Map<String,dynamic>'

**To Reproduce**
Siehe Beschreibungstext

**Device Information:**
 - Device: Xiaomi Redmi Note 11
 - OS: Android: 12 SKQ1.211006.001
 - Paperless Mobile version: kann
 Nicht sehen... Ist aktuell vom Googleplay
- Paperless Server version 1.5.0

**Additional context**
In der Version vom Johann Bauer (auch vom Googleplay) funktioniert der Login einwandfrei. Würde jedoch deine Version auch gerne testen, da sie mir vollständiger erscheint.

**Comment by astubenbord** [comment]
Thanks for creating a ticket.

I see that you are still on a very old paperless version. The API has changed in the meantime and due to the fact that many changes to the API were either not well documented or the API was not versioned accordingly, it is very hard for me to maintain compatibility with such old versions.

So I can only advise you to update paperless. Of course I try to support as many versions as possible, but the effort would just explode if I tried to cover every version, which I wouldn't be able to do on my own in terms of time.

If you want to stay on this version, then you would have to send me the logs of the app so I can look where the bug happens. You can easily view these via `flutter logs` or `adb logcat | grep flutter`. Just connect your phone, run one of the commands in the terminal and try to log in.

It is also possible that the error is not related to your paperless version. The bug has been reported before in another issue. I'll link it here in a moment.

EDITED: Translated to english

**Comment by hcgraf** [comment]
I can confirm that this error occurs with paperless-ng (last version 1.5.0), but not with paperless-ngx

EDITED by astubenbord: translated to english

**Comment by htpnikon** [comment]
It's done for me... Changed to the latest paperless-ngx server version. Problem does not occur anymore.

EDITED by astubenbord: Translated to english

**Comment by astubenbord** [comment]
@htpnikon Hi, ich frage das sehr ungern aber wäre es möglich, dass du deine Play Store Rezension noch aktualisierst? Der eine Stern zieht die Gesamtbewertung leider ziemlich runter, was ich schade finde :/

**Comment by htpnikon** [comment]
Erledigt!
