### ISSUE TITLE
[Bug] Pending Files view error/not cleaned

### ISSUE THREAD

**Issue by lagset** [astubenbord/paperless-mobile#268]
### What happened?

When uploading a file using the sharing options on Android 12 and then choosing paperless-mobile, the dialog for adding a new document opena correctly. As soon as the upload button is pressed a syste notification is triggered (upload pending) and the document is added to the "pending files" in the burger menu.

Shortly after the system notification for upload finished is triggered. However, the files remain in the "pending files" view in the app, even though they have been correctly uploaded (3.0.0 and 3.0.1)

With 3.0.3 I also found this error displayed in the "pending files" view:

![Screenshot_20231009-213915](https://github.com/astubenbord/paperless-mobile/assets/15156011/e69ca0da-5116-4105-944f-2ab4c63ebb50)

The upload itself however works fine without issues.

### Steps to reproduce

1. Upload a document using the sharing options of android 

### Paperless-ng*x Version

1.17.4

### Paperless-Mobile Version

3.0.x

### Device

Pixel 3a

### Operating System Version

Android 12

### Device Locale

english

### Selected Locale

None

**Comment by astubenbord** [comment]
Oops, yeah, you're correct. The route configurations are automatically generated since v3.0.3, I accidentally forgot to add the pending files route to the config. Thanks!

I'll check the other issue in the next couple of days, until then you'll unfortunately have to delete these files manually. 
EDIT: Okay, I found it. Fix is on it's way :)
