### ISSUE TITLE
[Bug]: Label query cannot be unselected 

### ISSUE THREAD

**Issue by SeedDMS** [astubenbord/paperless-mobile#271]
### What happened?

Resetting the filter criteria doesn't work for document type if there are no document types defined.

### Steps to reproduce

1. Ensure you have no document types defined
2. Open 'Filter Documents'
3. Select 'Document Type' though it is greyed out
4. Select one of 'not assigned' or 'any assigned'
5. Touch on the cross in the Document Type filter in order to remove the filter
6. The list from step 4. shows up again

It is not possible to remove that filter on Document Type unless you reset the complete filter. This does not happen if the field is not greyed out

### Paperless-ng*x Version

1.13.0

### Paperless-Mobile Version

3.0.2+49

### Device

xiaomi

### Operating System Version

Android 9

### Device Locale

german

### Selected Locale

English (US)

**Comment by astubenbord** [comment]
You're right, that's actually an edge case I didn't consider. So what would the expected behavior be?

Maybe the best idea would simply be to never disable these fields. The web interface also doesn't do that. For example, if I have a single document type and a saved view which just filters by this document type, the app currently doesn't consider that the field in the filter can be set through the selection of this view. Maybe I'll add a hint that the filter will return an empty result or so. 

Thanks for reporting.

**Comment by SeedDMS** [comment]
I wonder if a filter for document type (or correspondent, storage path) should be offered as a filter at all if not a single document type has ever been defined. Setting such a filter to "not assigned" will return all documents and setting it to "any assigned" will return no documents at all. That's not very useful.

**Comment by astubenbord** [comment]
Yeah, that's why I initially disabled these fields. However, I see the use case why someone might do that. Maybe you have an email rule and you're waiting for a certain document to be received, which will be assigned to a document type which has not yet been assigned to other documents. Then you might want to set the filter in app and periodically refresh instead of always having to check the filter dialog if it is available by now. 

I think it might make sense to show a hint indicating that selecting this filter will either show all or no documents. Same goes for the unassigned labels, where I may add a hint that this label is not assigned to any documents.

**Comment by SeedDMS** [comment]
If your are waiting for a document of a certain type, than this type must exist already to setup the filter. In my case there is no defined document type and the only choices are 'not assigned' or 'any assigned'. If I set up a filter for 'document type = any assigned' I could actually wait for the first document with a document type, but that's about the only use case I can make up.

**Comment by astubenbord** [comment]
Yes, the type has to exist, but e.g. I always create several types beforehand to be able to categorize my documents later on, so I don't have to create them on the fly. Also, even if it's a niche use case, the API allows it, so the app should be able to handle these cases. I'll go for a less restrictive direction with more hints on the number of documents a label is assigned to. 

It might make sense to disable the field if there are no document types at all, that might be an option. Would that be a compromise?

**Comment by astubenbord** [comment]
@SeedDMS Like this maybe?

![Screenshot_20231010-125440.png](https://github.com/astubenbord/paperless-mobile/assets/79228196/6b3c63ef-508c-4aab-bbce-6573ee057efa)

**Comment by SeedDMS** [comment]
Yes, I think disabling a filter field (document type, storage path, correspondent) would be the best choice if there is nothing to select than 'Not assigened' and 'Any assigned'

**Comment by astubenbord** [comment]
Okay, I changed it so that you can only edit the field if at least one selectable value exists in the filter.
