### ISSUE TITLE
[Feature]: Repect Android's reduced animation settings

### ISSUE THREAD

**Issue by UlyssesZh** [astubenbord/paperless-mobile#292]
### Description

Android offers ways to disable animations to make UIs more friendly to motion-sensitive people, so it is a great accessibility setting. One can reduce/disable animations in two ways:
- In developer settings, there are options for adjusting animation times for various types of animations.
- In some Android versions, there is a switch to toggle on removing animations in accessibility settings.

I hope Paperless Mobile to respect these settings to increase the accessibility of the app.

**Comment by astubenbord** [comment]
Hi, I don't think flutter provides an interface to get the different timings for certain types of animations, also because it's a developer setting which is not particularly meant to provide accessibility but rather debugging capabilities. However, I can disable animations depending on whether the user has them disabled in the accessibility settings or not. Shouldn't be that much effort also.

**Comment by astubenbord** [comment]
I implemented a new setting (which is also not translated to other languages since it is only meant as a temporary solution). There is an open issue where flutter does not correctly read the system setting for disabling animations. 

See https://github.com/flutter/flutter/issues/130976
