### ISSUE TITLE
[Bug]: Not connecting with latest paperless-ngx (2.3.0)

### ISSUE THREAD

**Issue by rubenixnagios** [astubenbord/paperless-mobile#345]
### What happened?

Just updated paperless-ngx to latest release.
docker image: ghcr.io/paperless-ngx/paperless-ngx:latest

remove / install paperless-mobile from Google app store

fill in server & credentials
a popup apears with message: Exception Api 4 not supported

### Steps to reproduce

it works from web

### Screenshots

![1704528820011](https://github.com/astubenbord/paperless-mobile/assets/72105987/19dbbac6-b2ae-42a1-9607-5530923c68d5)

### Paperless-ng*x Version

2.3.0

### Paperless-Mobile Version

3.1.8 (beta tester)

### Device

Xiaomi RedmiNote8 Pro

### Operating System Version

Android 11

### Device Locale

spanish

### Selected Locale

Spanish

**Comment by astubenbord** [comment]
Hi, since since endpoints evolve over time, the app has to know the API version of paperless to delegate the logic to the corresponding implementation. When the API version is incremented and the app is not updated, the current implementation does not fallback to the latest version. I'll add this fallback in the next release. However, I'm not entirely sure whether a server running api v4 is also capable of "communicating" in api v3. I've asked the devs, maybe it's straight forward...

**Comment by astubenbord** [comment]
Should be fixed in the latest release. Feel free to reopen if the issue persists.
