### ISSUE TITLE
[Bug]: Vorschau Bild des PDF Dokuments wird nicht angezeigt

### ISSUE THREAD

**Issue by ArneTK2415** [astubenbord/paperless-mobile#363]
### What happened?

Wenn ich auf das Miniatur Bild des PDF-Dokuments drücke, wird mir normalerweise das PDF-dokument angezeigt, so dass ich durchblättern kann.

Leider wird mir die Vorschau des Dokuments, durch dis ich durchblättern kann, nicht mehr angezeigt.

### Steps to reproduce

Auf das Miniatur Bild des Dokuments drücken, um es zu vergrößern und Durchblättern zu können.

### Screenshots

![Screenshot_20240112_214520](https://github.com/astubenbord/paperless-mobile/assets/156470502/61ba5b73-ff80-4b4e-9fee-55c89bec2796)

### Paperless-ng*x Version

2.1.3

### Paperless-Mobile Version

3.2.0+404

### Device

Samsung Galaxy S10

### Operating System Version

Android 12

### Device Locale

German

### Selected Locale

German

**Comment by sowaco** [comment]
I can confirm this problem with following setup:

**Paperless-ng*x Version**
2.3.3

**Paperless-Mobile Version**
3.2+404

**Device**
Xiaomi MI 8 Lite

**Operating System Version**
Android 10

**Device Locale**
German

This Issue seems to be a duplicate of https://github.com/astubenbord/paperless-mobile/issues/365

Here is a short screen record to clarify the issue:
https://github.com/astubenbord/paperless-mobile/assets/213020/54dc025e-dfbd-47a4-bfda-9e92718709b6

**Comment by KelvinGradCelsius** [comment]
Here same issue.

Paperless-ng*x Version
1.17.4

Paperless-Mobile Version
3.2.0+404

Device
Google Pixel 6a

Operating System Version
Android 14

Device Locale
German

Selected Locale
German

Additional Context
No response

**Comment by lagset** [comment]
Can confirm.

Paperless-mobile
3.2.0+404

Paperless-ngx
2.3.2

Hardware
Google Pixel 8

OS
Android 14

**Comment by astubenbord** [comment]
Closing as duplicate of #350
