### ISSUE TITLE
Download button does not work

### ISSUE THREAD

**Issue by jdckr** [astubenbord/paperless-mobile#39]
Is it me or does the download button not work on a documents overview page?

**Comment by astubenbord** [comment]
It should work, but flutter cannot download files to locations outside of its application directory. The files are stored in /android/data/de.astubenbord.paperless_mobile/files/Download.

Maybe check if it is there, otherwise I'll have to do some testing.

But it's a good point, there should be some feedback to the user, at least a snackbar or something indicating the location to which the file was downloaded to. I'll create a new ticket. Thanks.

**Comment by jdckr** [comment]
Yes, can find the files in the apps data directory. It is really confusing if nothing happens. My actual expectation was that it open in my installed pdf viewer. Don't know why, but this is how I was used to in the other apps.

**Comment by astubenbord** [comment]
Added notification in v1.3.0-beta
